environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\build.cmd"

  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      DISTUTILS_USE_SDK: "1"
      PYTHON: "3.8"

    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      DISTUTILS_USE_SDK: "1"
      PYTHON: "3.7"

    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      DISTUTILS_USE_SDK: "1"
      PYTHON: "3.6"

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: conda config --append channels conda-forge
  - cmd: conda create -n test_env python=%PYTHON%
  - cmd: conda activate test_env
  - cmd: python --version
  - cmd: pip install -U --pre pytest
  - cmd: pip install -r requirements-testing.txt
  - cmd: conda install udunits2 c-compiler
  - cmd: "%WITH_COMPILER% pip install ."

build: false

test_script:
  - pytest -vvv
