environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda38-x64
      PYTHON: "3.8"

    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      PYTHON: "3.7"

    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      PYTHON: "3.6"

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: conda config --append channels conda-forge
  - cmd: conda env create -n test_env python=$PYTHON
  - cmd: conda activate test_env
  - cmd: python --version
  - cmd: pip install . -r requirements-testing.txt
  - cmd: conda install pymt

build: false

test_script:
  - pytest -vvv
