[project]
name = "bmi_tester"
version = "0.5.11.dev0"
requires-python = ">=3.11"
description = "Test Python BMI bindings"
license = "MIT"
license-files = ["LICENSE.md"]
keywords = [
    "bmi",
    "csdms",
    "model",
    "python",
    "testing",
]
authors = [
    { name = "Eric Hutton", email = "huttone@colorado.edu" },
]
maintainers = [
    { name = "Eric Hutton", email = "huttone@colorado.edu"},
    { name = "Mark Piper", email = "mark.piper@colorado.edu"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "importlib-resources; python_version < '3.12'",
    "model-metadata>=0.8.1",
    "numpy",
    "packaging",
    "pytest>=8.0.0",
    "pytest-dependency",
    "standard-names>=0.2.8",
]
dynamic = [
    "readme",
]

[project.optional-dependencies]
units = [
	"gimli.units>=0.4.1"
]
dev = [
    "nox",
]
testing = [
    "coveralls",
    "pytest-cov",
    "pytest",
]
docs = [
    "sphinx>=1.5.1",
]
build = [
    "build",
    "twine",
    "zest.releaser",
]

[project.urls]
Changelog = "https://github.com/csdms/bmi-tester/blob/master/CHANGES.rst"
Documentation = "https://bmi-tester.readthedocs.io/"
Homepage = "https://csdms.colorado.edu"
Repository = "https://github.com/csdms/bmi-tester"

[project.scripts]
bmi-test = "bmi_tester.main:main"

[project.entry-points."bmi.plugins"]
bmi_test = "bmi_tester.main:configure_parser_test"

[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.isort]
combine_as_imports = true
profile = "black"

[tool.pytest.ini_options]
minversion = "8.0.0"
testpaths = [
    "tests",
]
norecursedirs = [
    ".*",
    "*.egg*",
    "build",
    "dist",
]
addopts = [
    "--ignore=bmi_tester/bootstrap",
    "--ignore=bmi_tester/tests",
    "--tb=native",
    "--strict-markers",
    "--durations=16",
    "--doctest-modules",
    "-vvv",
]
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ALLOW_UNICODE",
]

[tool.zest-releaser]
tag-format = "v{version}"
python-file-with-version = "src/bmi_tester/_version.py"

[tool.black]
target-version = ["py311"]
