name: Documentation

on:
    push:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CHANGES.rst"
            - "CONTRIBUTING.rst"
            - "LICENSE.rst"
            - "README.rst"
    pull_request:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CHANGES.rst"
            - "CONTRIBUTING.rst"
            - "LICENSE.rst"
            - "README.rst"

jobs:
    build:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch. Without this if check, checks are duplicated since
        # internal PRs match both the push and pull_request events.
        if:
          github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
          github.repository
    
        runs-on: ubuntu-latest
        
        defaults:
          run:
            shell: bash -l {0}

        steps:
          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
              auto-update-conda: true
              python-version: ${{ matrix.python-version }}
              mamba-version: "*"
              channels: conda-forge,defaults
              channel-priority: true

          - name: Install requirements
            run: |
              mamba install --file=requirements.txt --file=requirements-docs.txt
              mamba install gimli.units
              mamba info
              mamba list

          - name: Install package
            run: |
              pip install -e .

          - name: Build documentation
            run: |
              make docs
